image: yueyehua/debian-kitchen

lines_length:
  script:
    - >
      bash <(curl -s
      https://gitlab.com/yue-script/checks/raw/master/check_lines_length.sh)

git_history:
  script:
    - >
      bash <(curl -s
      https://gitlab.com/yue-script/checks/raw/master/check_git_history.sh)
